- name: install cronjob for master backups
  k8s:
    state: "{{ backup_state }}"
    definition: "{{ lookup('template', role_path  + '/templates/cronjob-master.yaml.j2', template_vars=dict(master=master)) }}"
  delegate_to: "{{ master }}"
  loop: "{{ groups[m7s_k8s_backups_ansible_k8s_master_group] }}"
  loop_control:
    loop_var: master

- name: install configmap with backup scripts
  k8s:
    state: "{{ backup_state }}"
    definition: "{{ lookup('template', role_path  + '/templates/configmap.yaml.j2') }}"
  run_once: true
  delegate_to: "{{ master }}"
  loop: "{{ groups[m7s_k8s_backups_ansible_k8s_master_group] }}"
  loop_control:
    loop_var: master
