- name: setup etcd backup script
  template:
    src: "{{ role_path  + '/templates/etcd-backup.sh.j2' }}"
    dest: '/usr/local/bin/etcd-backup.sh'
    mode: '0700'
    owner: root

- name: setup etcd keys backup script
  template:
    src: "{{ role_path  + '/templates/etcd-keys-backup.sh.j2' }}"
    dest: '/usr/local/bin/etcd-keys-backup.sh'
    mode: '0700'
    owner: root

- name: install etcd backup cronjob
  cron:
    name: backup etcd
    state: "{{ backup_state}}"
    minute: "{{ m7s_k8s_backups_etcd_minute_schedule }}"
    job: /usr/local/bin/etcd-backup.sh

- name: install ectd keys backup cronjob
  cron:
    name: backup etcd keys
    state: "{{ backup_state}}"
    special_time: "{{ m7s_k8s_backups_etcd_keys_special_time_schedule }}"
    job: /usr/local/bin/etcd-keys-backup.sh

- name: install clean backups cronjob
  cron:
    name: clean old backups
    state: "{{ backup_state }}"
    special_time: "{{ m7s_k8s_backups_etcd_keys_special_time_schedule }}"
    job: "find {{ m7s_k8s_backups_destination }}/* -mtime +{{ m7s_k8s_backups_retain }} -exec rm {} \\;"
