---
# tasks file for k8s-backup

- name: include etcd task backup
  include_tasks: backup-master.yml

- name: include etcd task backup
  include_tasks: backup-etcd.yml

- name: install configmap for etcd backups
  k8s:
    state: "{{ 'present' if k8s_backups_enabled else 'absent' }}"
    definition: "{{ lookup('template', role_path  + '/templates/configmap.yaml.j2') }}"
  run_once: true
  delegate_to: "{{ master }}"
  loop: "{{ groups['kube-master'] }}"
  loop_control: 
    loop_var: master