---

- name: Set backup_state to present
  set_fact:
    backup_state: 'present'
  when: m7s_k8s_backups_state is not defined or m7s_k8s_backups_state in [ 'present', 'installed' ]

- name: set backup_state to absent
  set_fact:
    backup_state: 'absent'
  when:
  - m7s_k8s_backups_state is defined
  - m7s_k8s_backups_state == 'absent'

- name: Create destination directory
  file:
    path: "{{ m7s_k8s_backups_destination }}"
    state: directory
    mode: '0700'

- name: Setup master task backup
  include_tasks: backup-master.yml
  when: inventory_hostname in groups[m7s_k8s_backups_ansible_k8s_master_group]

- name: Setup etcd task backup
  include_tasks: backup-etcd.yml
  when: inventory_hostname in groups[m7s_k8s_backups_ansible_k8s_etcd_group]

